apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
    kubernetes.io/ingress.global-static-ip-name: ingress-address
spec:
  defaultBackend:
    service:
      name: springboot-employee-demo
      port:
        number: 80