apiVersion: v1
kind: Service
metadata:
  name: springboot-employee-demo
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: springboot-employee-demo
  type: ClusterIP
